#!/usr/bin/with-contenv bash

web_client_path="$(find /usr/lib/plexmediaserver/ -name WebClient.bundle)/Contents/Resources/js"

file_to_edit=$(du -a "$web_client_path" | sort -hr | sed -n '2{p;q}' | awk '{print $2}')

echo "Adding Auto Skip Intro"
sed -i 's/onTouchStart: mP/onTouchStart: mP,onFocus: y/g' "$file_to_edit"
